Add SUSFS patch application step for KernelSU
Added a step to apply SUSFS patches for KernelSU variants in the workflow.

diff --git a/.github/workflows/SUSFS GKI.yml b/.github/workflows/SUSFS GKI.yml
--- a/.github/workflows/SUSFS GKI.yml
+++ b/.github/workflows/SUSFS GKI.yml
@@ -370,6 +370,34 @@ jobs:
       # --------------------------------------------------
       # SUSFS FIX PATCHES (OPTIONAL / SAFE)
       # --------------------------------------------------
+
+      - name: Apply SUSFS Patches for KernelSU Variants
+        run: |
+           echo "Changing to configuration directory: $CONFIG..."
+           cd "$CONFIG"
+
+           echo "Applying SUSFS patches..."
+
+           # Copy SUSFS patches
+           cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ inputs.android_version }}-${{ inputs.kernel_version }}.patch ./common/
+           cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/
+           cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
+
+           if [ "${{ inputs.kernelsu_variant }}" == "SukiSU" ]; then
+             echo "Applying SUSFS patches for SukiSU..."
+              cd KernelSU
+            
+            
+             echo "Applying SukiSU specific SUSFS patch..."
+           else
+             echo "Invalid KernelSU variant selected!"
+             exit 1
+           fi
+
+           # Change to common directory and apply common SUSFS patch
+           cd ../common
+           patch --fuzz=3 -p1 < 50_add_susfs_in_gki-${{ inputs.android_version }}-${{ inputs.kernel_version }}.patch || true
+
       
       - name: Apply SUSFS fix patches (REQUIRED)
         working-directory: ${{ env.KERNEL_ROOT }}/common
@@ -442,33 +470,6 @@ jobs:
             grep -A 5 "bad_version:" "$TARGET_FILE" || true
             exit 1
           fi
-
-      # - name: Apply SUSFS Patches for KernelSU Variants
-      #   run: |
-      #     echo "Changing to configuration directory: $CONFIG..."
-      #     cd "$CONFIG"
-
-      #     echo "Applying SUSFS patches..."
-
-      #     # Copy SUSFS patches
-      #     cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ inputs.android_version }}-${{ inputs.kernel_version }}.patch ./common/
-      #     cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/
-      #     cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
-
-      #     if [ "${{ inputs.kernelsu_variant }}" == "SukiSU" ]; then
-      #       echo "Applying SUSFS patches for SukiSU..."
-      #        cd KernelSU
-            
-            
-      #       echo "Applying SukiSU specific SUSFS patch..."
-      #     else
-      #       echo "Invalid KernelSU variant selected!"
-      #       exit 1
-      #     fi
-
-      #     # Change to common directory and apply common SUSFS patch
-      #     cd ../common
-      #     patch --fuzz=3 -p1 < 50_add_susfs_in_gki-${{ inputs.android_version }}-${{ inputs.kernel_version }}.patch || true
 
       - name: Apply New Hooks Patches
         run: |
